# Generated by Django 4.0.3 on 2022-03-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Form',
            new_name='FormDemo',
        ),
    ]
