# Generated by Django 4.0.3 on 2022-03-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_api_delete_formdemo'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='pic',
            field=models.ImageField(default='happy', upload_to=''),
            preserve_default=False,
        ),
    ]
